
package com.mycompany.analizador;


public enum TipoToken {
    PALABRA_RESERVADA,
    PALABRAS_BOOL,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    OPERADOR_INC_DEC,
    ID,
    NUMERO,
    CADENA,
    IGUAL,
    PARENTESIS_AP,
    PARENTESIS_CIERRE,
    LLAVE_AP,
    LLAVE_CIERRE,
    FIN_DE_LINEA,
    DESCONOCIDO,
    NUMERO_F,
    COMILLA_DOBLE,
    PUNTO
}
